spring.application.name=TextToSQL

# Supabase PostgreSQL Direct Connection
spring.datasource.url=${Database_URL}
spring.datasource.username=${Database_USERNAME}
spring.datasource.password=${Database_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
supabase.url=${Supabase_URL}
supabase.secret-key=${Supabase_SECRET}
supabase.storage.bucket=${Supabase_BUCKET}


# Groq - OpenAI Compatible API
spring.ai.openai.api-key=${Openai_APIKEY}
spring.ai.openai.base-url=${Openai_URL}

# Default Groq model
spring.ai.openai.chat.model=${Openai_MODEL}
spring.ai.openai.chat.temperature=${Openai_TEMPERATURE}
# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
# Custom JWT Secret
jwt.secret=${JWT_SECRET}

